package es.upm.dit.isst.medconweb;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;

public class RegistrollegadapacientesTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "/home/isst/chromedriver");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void registrollegadapacientes() {
    driver.get("http://localhost:8080/pacientes");
    driver.findElement(By.id("cipa")).click();
    driver.findElement(By.id("cipa")).sendKeys("8475291432");
    driver.findElement(By.cssSelector(".button")).click();
    driver.findElement(By.xpath("//span[contains(.,\'Carlos\')]")).click();
    driver.findElement(By.linkText("Salir")).click();
    driver.findElement(By.id("cipa")).click();
    driver.findElement(By.id("cipa")).sendKeys("7331089076");
    driver.findElement(By.cssSelector(".button")).click();
    driver.findElement(By.xpath("//span[contains(.,\'Ana\')]")).click();
    driver.findElement(By.xpath("//a[contains(@href, \'/pacientes\')]")).click();
    driver.findElement(By.id("cipa")).click();
    driver.findElement(By.id("cipa")).sendKeys("6789011234");
    driver.findElement(By.cssSelector(".button")).click();
    driver.findElement(By.xpath("//span[contains(.,\'Guillermo\')]")).click();
    driver.findElement(By.linkText("Salir")).click();
  }
}
